### PR TITLE
Add support to parse WoW64 32-bit modules

### PR DESCRIPTION
**Pull request by ducphanduyagentp**
Adding support to parse 32-bit modules in WoW64 dumps. My Rust skills are kindergarten level so please help me review this :joy:

Thanks!

### CODE REVIEW

**Comment by 0vercl0k** [comment]
@ducphanduyagentp I worked on that PR today trying to clean things up / simplify / factorize some of the code. Please let me know if I broke something 😅

If not I'll look into adding tests & merge that!

Thanks again for the contribution 👏🏽

Cheers

**Comment by ducphanduyagentp** [comment]
Hey sorry for the delay. I'll try it out and let you know soon!

**Comment by 0vercl0k** [comment]
No worries, take your time, cheers 🫡

**Comment by 0vercl0k** [comment]
all right i did add some kind of testing, merging

**Pull request merged**
